---
- name: Create Virtual Machine
  hosts: localhost
  tasks:
    - name: Check input vars
      debug:
        msg: 
          - "subscription: {{ subscription }}"
          - "location: {{ location }}"
          - "rg_name: {{ rg_name }}"
          - "user_id: {{ user_id }}"

    - name: Create Resource Group
      shell: az group create \
        --name {{ rg_name }} \
        --location {{ location }} \
        --subscription {{ subscription }} \
        --tags user_id={{ user_id }}
      register: create_rg
      tags: create_rg

    - name: Resource Group Created
      debug:
        var: create_rg
      tags: create_rg

    - name: Delete Resource Group
      shell: az group delete \
        --name {{ rg_name }} \
        --subscription {{ subscription }} \
        --yes
      register: delete_rg
      tags: delete_rg

    - name: Resource Group Deleted
      debug:
        var: delete_rg
      tags: delete_rg
