---
- name: Check input vars create_rg
  debug:
    msg: 
      - "subscription: {{ subscription }}"
      - "location: {{ location }}"
      - "rg_name: {{ rg_name }}"
      - "user_id: {{ user_id }}"
  tags: create_rg

- name: Create Resource Group
  shell: az group create \
    --name {{ rg_name }} \
    --location {{ location }} \
    --subscription {{ subscription }} \
    --tags user_id={{ user_id }}
  register: create_rg
  tags: create_rg

- name: Resource Group Created
  debug:
    var: create_rg
  tags: create_rg
