---
- name: Check input vars create_rg
  debug:
    msg: 
      - "subscription: {{ subscription }}"
      - "location: {{ location }}"
      - "rg_name: {{ rg_name }}"
      - "user_id: {{ user_id }}"
      
- name: Create Resource Group
  azure_rm_resourcegroup:
    name: ansible-rg
    location: eastus
  register: create_rg

- name: Resource Group Created
  debug:
    var: create_rg