---
- name: Check input vars create_rg
  debug:
    msg:
      - "location: {{ location }}"
      - "rg_name: {{ rg_name }}"
      
- name: Create Resource Group
  azure_rm_resourcegroup:
    name: "{{ rg_name }}"
    location: "{{ location }}"
  register: create_rg

- name: Resource Group Created
  debug:
    var: create_rg