---
- name: Check input vars delete_rg
  debug:
    msg: 
      - "subscription: {{ subscription }}"
      - "rg_name: {{ rg_name }}"
  tags: delete_rg

- name: Delete Resource Group
  shell: az group delete \
    --name {{ rg_name }} \
    --subscription {{ subscription }} \
    --yes
  register: delete_rg
  tags: delete_rg

- name: Resource Group Deleted
  debug:
    var: delete_rg
  tags: delete_rg
