---
- name: Install package azure-cli
  become: true
  become_user: root
  shell: apt install azure-cli -y
  register: install_azure

- name: Installation Result
  debug:
    var: install_azure

- name: Test az cli
  shell: az --version
  register: test_az_cli

